<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fate</string>
	</array>
	<key>name</key>
	<string>Fate</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#fate</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>(#.*$)</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(self|true|false|global)\b</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(([1-9][0-9]*|[0-9])(\.[0-9]+)?([eE][+-]?[0-9])?)</string>
					<key>name</key>
					<string>constant.numeric</string>
				</dict>
			</array>
		</dict>
		<key>expression</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#keyword</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#identifier</string>
				</dict>
			</array>
		</dict>
		<key>fate</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#expression</string>
				</dict>
			</array>
		</dict>
		<key>identifier</key>
		<dict>
			<key>match</key>
			<string>\b((\w|[$_])(\w|\d|[$_])*)\b</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<key>interpolation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\%([1-9][0-9]*|[0-9])(\|(\w|[$_])(\w|\d|[$_])*)*;?</string>
					<key>name</key>
					<string>variable.parameter.index</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\%((\w|[$_])(\w|\d|[$_])*)(\|(\w|[$_])(\w|\d|[$_])*)*;?</string>
					<key>name</key>
					<string>variable.parameter.name</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\%(\|(\w|[$_])(\w|\d|[$_-])*)*;?</string>
					<key>name</key>
					<string>variable.parameter.position</string>
				</dict>
			</array>
		</dict>
		<key>keyword</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(and|or|like|mod|not|if|unless|else)\b</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([\-~?+*\/|:@=(),\.\[\]&lt;&gt;{}])</string>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</array>
		</dict>
		<key>ml-string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>\"\"\"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\"\"\"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.triple</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<key>ml-string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'''</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'''</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.triple</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<key>statement</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(for|def|do|await|any|all|when|case|match|from|import|export|let|if|unless|as|in|else|end|where|select|return|reduce)\b</string>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</array>
		</dict>
		<key>string</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#ml-string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ml-string-single-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-double-quoted</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string-single-quoted</string>
				</dict>
			</array>
		</dict>
		<key>string-double-quoted</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
		<key>string-single-quoted</key>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin</string>
				</dict>
			</dict>
			<key>end</key>
			<string>'</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.single</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#interpolation</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.fate</string>
	<key>uuid</key>
	<string>b059aca9-7261-413b-a3f7-1c453843ca89</string>
</dict>
</plist>
